[build]
  # Set the directory that contains your built site files.
  # Since your index.html is in the root, we use "."
  publish = "."
  
  # Specify the directory for your serverless functions.
  functions = "netlify/functions"

# This rule makes your serverless function available at a clean URL.
# It rewrites requests from "/api/..." to your function file.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
