[build]
  # This command tells Netlify to run the "build" script from your package.json.
  # That script will complete successfully, satisfying the build process.
  command = "npm run build"
  
  # This explicitly tells Netlify your finished site (index.html, etc.) is in the root directory.
  # This is the crucial setting that should override any conflicting defaults.
  publish = "."
  
  # This tells Netlify where to find your serverless function.
  functions = "netlify/functions"

# This rule makes your serverless function available at a clean URL for your frontend to use.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
