[build]
  # This command runs the "build" script from your package.json,
  # which creates the "dist" directory.
  command = "npm run build"
  
  # This is the crucial line: it tells Netlify to deploy the
  # contents of the "dist" directory that the build command creates.
  publish = "dist"
  
  # This tells Netlify where to find your serverless function.
  functions = "netlify/functions"

# This rewrite rule makes your serverless function available
# at a clean URL for your frontend to use.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

