[build]
  # This command overrides the Netlify UI settings. 
  # It's a placeholder that does nothing but successfully completes.
  command = "echo 'No build step required'"
  
  # The directory to publish. Since index.html is in the root, we use "."
  publish = "."
  
  # The directory where your serverless function is.
  functions = "netlify/functions"

# This rule makes your serverless function available at a clean URL.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
